theme: jekyll-theme-cayman
title: Volunteer Portal
favicon_file: public/favicon.ico
demo_url: https://volunteer-portal-demo.herokuapp.com
slack_invite_link: https://join.slack.com/t/zendesk-volunteer/shared_invite/enQtMzYzNTIzMDUwNDE5LWUzNzQzMjgwZTdmNDBiZDI3ZmUxZDlhN2MwMzJlMjMyYTQ1MTg1OTUxZWYzM2FjZGYxNzhjM2YwYzYyOTE3YjY
